---
sidebar: sidebar 
permalink: task-manage-volumes.html 
keywords: azure netapp files, delete volumes, delete nfs volumes, netapp account, capacity pool, change service level 
summary: Depois de configurar o ambiente de trabalho, você pode gerenciar contas do Azure NetApp Files, pools de capacidade, volumes e snapshots. 
---
= Gerenciar volumes existentes
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Você pode gerenciar volumes existentes conforme suas necessidades de storage mudam. Você pode editar volumes, alterar o nível de serviço de um volume, gerenciar cópias Snapshot e excluir volumes.



== Edite o tamanho e as tags de um volume

Depois de criar um volume, você pode modificar seu tamanho e tags a qualquer momento.

.Passos
. Abra o ambiente de trabalho.
. Passe o Mouse sobre o volume e selecione *Editar*.
. Modifique o tamanho e as tags conforme necessário.
. Clique em *aplicar*.




== Altere o nível de serviço do volume

Depois de criar um volume, você pode alterar o nível de serviço a qualquer momento, desde que o pool de capacidade de destino já exista.

.Passos
. Abra o ambiente de trabalho.
. Passe o Mouse sobre o volume e selecione *alterar nível de serviço*.
. Selecione o pool de capacidade que fornece o nível de serviço desejado.
. Clique em *alterar*.


.Resultado
O volume é movido para o outro pool de capacidade sem afetar o volume.



== Gerenciar cópias Snapshot

As cópias Snapshot fornecem uma cópia pontual do volume. Criar cópias Snapshot, restaurar os dados para um novo volume e excluir cópias Snapshot.

.Passos
. Abra o ambiente de trabalho.
. Passe o Mouse sobre o volume e escolha uma das opções disponíveis para gerenciar cópias Snapshot:
+
** *Criar uma cópia Snapshot*
** *Reverter volume para Snapshot*
** *Excluir uma cópia Snapshot*


. Siga as instruções para concluir a ação selecionada.




== Eliminar volumes

Exclua os volumes que você não precisa mais.

.Passos
. Abra o ambiente de trabalho.
. Passe o Mouse sobre o volume e clique em *Excluir*.
. Confirme se pretende eliminar o volume.

