---
sidebar: sidebar 
permalink: whats-new.html 
keywords: 'what"s new, features, new, release notes, bugs, limitations, known issues, enhancements, fixes' 
summary: Saiba o que há de novo com o suporte do Azure NetApp Files no BlueXP . 
---
= O que há de novo
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Saiba o que há de novo com o Azure NetApp Files no BlueXP .



== 13 de janeiro de 2024



=== Recursos de rede agora suportados no BlueXP 

Ao configurar um volume no Azure NetApp Files a partir do BlueXP , agora você pode indicar recursos de rede. Isso se alinha à funcionalidade disponível no Azure NetApp Files nativo.



== 11 de abril de 2021



=== Suporte para modelos de volume

Um novo serviço modelos de aplicativos permite configurar um modelo de volume para o Azure NetApp Files. O modelo deve facilitar o trabalho porque certos parâmetros de volume já serão definidos no modelo, como pool de capacidade, tamanho, protocolo, VNet e sub-rede onde o volume deve residir e muito mais. Quando um parâmetro já está predefinido, você pode simplesmente pular para o próximo parâmetro de volume.



=== Suporte para modelos de volume

Um novo serviço modelos de aplicativos permite configurar um modelo de volume para o Azure NetApp Files. O modelo deve facilitar o trabalho porque certos parâmetros de volume já serão definidos no modelo, como pool de capacidade, tamanho, protocolo, VNet e sub-rede onde o volume deve residir e muito mais. Quando um parâmetro já está predefinido, você pode simplesmente pular para o próximo parâmetro de volume.

* https://docs.netapp.com/us-en/bluexp-remediation/concept-resource-templates.html["Saiba mais sobre modelos de aplicativos e como usá-los em seu ambiente"^]
* https://docs.netapp.com/us-en/bluexp-azure-netapp-files/task-create-volumes.html["Saiba como criar um volume Azure NetApp Files a partir de um modelo"]




== 8 de março de 2021



=== Alterar dinamicamente os níveis de serviço

Agora você pode alterar dinamicamente o nível de serviço de um volume para atender às necessidades de workload e otimizar seus custos. O volume é movido para o outro pool de capacidade sem afetar o volume.

https://docs.netapp.com/us-en/bluexp-azure-netapp-files/task-manage-volumes.html#change-the-volumes-service-level["Saiba como alterar o nível de serviço de um volume"].



== 3 de agosto de 2020



=== Configuração e gerenciamento do Azure NetApp Files

Configure e gerencie o Azure NetApp Files diretamente do Cloud Manager. Depois de criar um ambiente de trabalho do Azure NetApp Files, você pode concluir as seguintes tarefas:

* Criar volumes NFS e SMB.
* Gerenciar pools de capacidade e snapshots de volume
+
O Cloud Manager permite criar, excluir e restaurar snapshots de volume. Você também pode criar novos pools de capacidade e especificar seus níveis de serviço.

* Edite um volume alterando seu tamanho e gerenciando tags.


A capacidade de criar e gerenciar o Azure NetApp Files diretamente do Cloud Manager substitui o recurso de migração de dados anterior.



== 5 de abril de 2020



=== Migração de dados para o Azure NetApp Files

Agora é possível migrar dados NFS ou SMB para o Azure NetApp Files diretamente do Cloud Manager. As sincronizações de dados são alimentadas por cópia e sincronização do BlueXP .
